// <auto-generated />
using System;
using Group3Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group3Flight.Migrations
{
    [DbContext(typeof(FlightDatabaseContext))]
    [Migration("20260414160328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Group3Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airline");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "emirates.png",
                            Name = "Emirates"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "qatar_airways.png",
                            Name = "Qatar Airways"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "lufthansa.png",
                            Name = "Lufthansa"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "air_france.png",
                            Name = "Air France"
                        },
                        new
                        {
                            AirlineId = 5,
                            ImageName = "singapore_airlines.png",
                            Name = "Singapore Airlines"
                        },
                        new
                        {
                            AirlineId = 6,
                            ImageName = "etihad_airways.png",
                            Name = "Etihad Airways"
                        });
                });

            modelBuilder.Entity("Group3Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 777",
                            AirlineId = 2,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 2, 0, 0, 0),
                            Emission = 650.5,
                            FlightCode = "EK601",
                            From = "Dubai",
                            Price = 1500,
                            To = "New York"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Boeing 787 Dreamliner",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 14, 45, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 9, 15, 0, 0),
                            Emission = 420.30000000000001,
                            FlightCode = "QR702",
                            From = "Doha",
                            Price = 800,
                            To = "London"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Boeing 747",
                            AirlineId = 4,
                            ArrivalTime = new TimeSpan(0, 16, 30, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 13, 0, 0, 0),
                            Emission = 700.0,
                            FlightCode = "LH803",
                            From = "Frankfurt",
                            Price = 1800,
                            To = "Chicago"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Airbus A380",
                            AirlineId = 3,
                            ArrivalTime = new TimeSpan(0, 15, 0, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 7, 30, 0, 0),
                            Emission = 500.0,
                            FlightCode = "AF904",
                            From = "Paris",
                            Price = 950,
                            To = "Dubai"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Airbus A350",
                            AirlineId = 5,
                            ArrivalTime = new TimeSpan(0, 6, 30, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 20, 0, 0, 0),
                            Emission = 900.0,
                            FlightCode = "SQ1005",
                            From = "Singapore",
                            Price = 2000,
                            To = "Dubai"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "Boeing 787",
                            AirlineId = 6,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 22, 15, 0, 0),
                            Emission = 950.0,
                            FlightCode = "EY1106",
                            From = "Abu Dhabi",
                            Price = 2200,
                            To = "Sydney"
                        });
                });

            modelBuilder.Entity("Group3Flight.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("FlightId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Group3Flight.Models.Flight", b =>
                {
                    b.HasOne("Group3Flight.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group3Flight.Models.Reservation", b =>
                {
                    b.HasOne("Group3Flight.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
